BEGIN;

DROP TABLE IF EXISTS volunteer_activities CASCADE;
DROP TABLE IF EXISTS donations CASCADE;
DROP TABLE IF EXISTS activities CASCADE;
DROP TABLE IF EXISTS activity_categories CASCADE;
DROP TABLE IF EXISTS coordinators CASCADE;
DROP TABLE IF EXISTS volunteers CASCADE;
DROP TABLE IF EXISTS ongs CASCADE;
DROP TABLE IF EXISTS users CASCADE;

COMMIT;